/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Script } from "./Script";
import { ScriptCountArgs } from "./ScriptCountArgs";
import { ScriptFindManyArgs } from "./ScriptFindManyArgs";
import { ScriptFindUniqueArgs } from "./ScriptFindUniqueArgs";
import { CreateScriptArgs } from "./CreateScriptArgs";
import { UpdateScriptArgs } from "./UpdateScriptArgs";
import { DeleteScriptArgs } from "./DeleteScriptArgs";
import { DeploymentFindManyArgs } from "../../deployment/base/DeploymentFindManyArgs";
import { Deployment } from "../../deployment/base/Deployment";
import { ScriptService } from "../script.service";
@graphql.Resolver(() => Script)
export class ScriptResolverBase {
  constructor(protected readonly service: ScriptService) {}

  async _scriptsMeta(
    @graphql.Args() args: ScriptCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Script])
  async scripts(@graphql.Args() args: ScriptFindManyArgs): Promise<Script[]> {
    return this.service.scripts(args);
  }

  @graphql.Query(() => Script, { nullable: true })
  async script(
    @graphql.Args() args: ScriptFindUniqueArgs
  ): Promise<Script | null> {
    const result = await this.service.script(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Script)
  async createScript(@graphql.Args() args: CreateScriptArgs): Promise<Script> {
    return await this.service.createScript({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Script)
  async updateScript(
    @graphql.Args() args: UpdateScriptArgs
  ): Promise<Script | null> {
    try {
      return await this.service.updateScript({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Script)
  async deleteScript(
    @graphql.Args() args: DeleteScriptArgs
  ): Promise<Script | null> {
    try {
      return await this.service.deleteScript(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Deployment], { name: "deployments" })
  async findDeployments(
    @graphql.Parent() parent: Script,
    @graphql.Args() args: DeploymentFindManyArgs
  ): Promise<Deployment[]> {
    const results = await this.service.findDeployments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
